<?php
/**
 * Hub setup wizard — run once, then self-destructs.
 * Visit /hub/setup.php, fill in credentials, and it will:
 *   1. Write hub/config.php
 *   2. Create the clients + usage tables
 *   3. Delete itself
 */

$configPath = __DIR__ . '/config.php';
$selfPath   = __FILE__;

// If config already exists, bail early (setup already done)
if (file_exists($configPath)) {
    die('<pre style="font-family:monospace;padding:2rem">Setup already complete — config.php exists.
Delete config.php to re-run setup (this will NOT drop your tables).</pre>');
}

$errors  = [];
$success = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $dbHost    = trim($_POST['db_host'] ?? 'localhost');
    $dbName    = trim($_POST['db_name'] ?? '');
    $dbUser    = trim($_POST['db_user'] ?? '');
    $dbPass    = $_POST['db_pass'] ?? '';
    $apiKey    = trim($_POST['anthropic_api_key'] ?? '');
    $adminPass = $_POST['admin_password'] ?? '';
    $hubUrl    = rtrim(trim($_POST['hub_url'] ?? ''), '/');

    if (!$dbName)    $errors[] = 'Database name is required.';
    if (!$dbUser)    $errors[] = 'Database user is required.';
    if (!$apiKey)    $errors[] = 'Anthropic API key is required.';
    if (strlen($adminPass) < 10) $errors[] = 'Admin password must be at least 10 characters.';
    if (!$hubUrl)    $errors[] = 'Hub URL is required.';

    if (empty($errors)) {
        // Test database connection
        try {
            $pdo = new PDO(
                "mysql:host=$dbHost;dbname=$dbName;charset=utf8mb4",
                $dbUser, $dbPass,
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );
        } catch (PDOException $e) {
            $errors[] = 'Database connection failed: ' . $e->getMessage();
        }
    }

    if (empty($errors)) {
        // Create tables
        try {
            $pdo->exec("
                CREATE TABLE IF NOT EXISTS clients (
                    id                    INT AUTO_INCREMENT PRIMARY KEY,
                    name                  VARCHAR(255) NOT NULL,
                    domain                VARCHAR(255) NOT NULL,
                    hub_api_key           VARCHAR(64)  NOT NULL UNIQUE,
                    status                ENUM('active','suspended','cancelled') DEFAULT 'active',
                    monthly_token_limit   INT DEFAULT 150000,
                    claude_model          VARCHAR(100) DEFAULT 'claude-sonnet-4-6',
                    stripe_customer_id    VARCHAR(255) DEFAULT NULL,
                    stripe_subscription_id VARCHAR(255) DEFAULT NULL,
                    notes                 TEXT DEFAULT NULL,
                    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
            ");
            $pdo->exec("
                CREATE TABLE IF NOT EXISTS usage (
                    id              INT AUTO_INCREMENT PRIMARY KEY,
                    client_id       INT  NOT NULL,
                    year_month      CHAR(7) NOT NULL,
                    tokens_used     INT DEFAULT 0,
                    requests_count  INT DEFAULT 0,
                    UNIQUE KEY client_month (client_id, year_month),
                    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
            ");
        } catch (PDOException $e) {
            $errors[] = 'Table creation failed: ' . $e->getMessage();
        }
    }

    if (empty($errors)) {
        // Hash admin password
        $hashedPass = password_hash($adminPass, PASSWORD_BCRYPT);

        // Write config.php
        $config = <<<PHP
<?php
// Hub configuration — generated by setup.php
// Do NOT commit this file.

define('DB_HOST',            '$dbHost');
define('DB_NAME',            '$dbName');
define('DB_USER',            '$dbUser');
define('DB_PASS',            '$dbPass');
define('ANTHROPIC_API_KEY',  '$apiKey');
define('HUB_ADMIN_PASSWORD', '$hashedPass');
define('HUB_URL',            '$hubUrl');
PHP;

        if (file_put_contents($configPath, $config) === false) {
            $errors[] = 'Could not write config.php — check directory permissions.';
        } else {
            $success = true;
            // Self-destruct
            @unlink($selfPath);
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Hub Setup</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, sans-serif; background: #0f172a; color: #e2e8f0;
         display: flex; align-items: flex-start; justify-content: center;
         min-height: 100vh; padding: 3rem 1rem; }
  .card { background: #1e293b; border: 1px solid #334155; border-radius: 12px;
          padding: 2.5rem; width: 100%; max-width: 520px; }
  h1 { font-size: 1.4rem; font-weight: 700; color: #f1f5f9; margin-bottom: 0.4rem; }
  .sub { color: #64748b; font-size: 0.875rem; margin-bottom: 2rem; }
  .field { margin-bottom: 1.25rem; }
  label { display: block; font-size: 0.8rem; color: #94a3b8; margin-bottom: 0.4rem; }
  .hint { font-size: 0.72rem; color: #475569; margin-top: 0.3rem; }
  input { width: 100%; padding: 0.6rem 0.85rem; background: #0f172a;
          border: 1px solid #334155; border-radius: 6px; color: #f1f5f9;
          font-size: 0.9rem; outline: none; }
  input:focus { border-color: #6366f1; }
  button { width: 100%; padding: 0.75rem; background: #6366f1; color: #fff;
           border: none; border-radius: 6px; font-size: 1rem; cursor: pointer;
           font-weight: 500; margin-top: 0.5rem; }
  button:hover { background: #4f46e5; }
  .divider { border: none; border-top: 1px solid #334155; margin: 1.5rem 0; }
  .section { font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.05em;
             color: #64748b; margin-bottom: 1rem; }
  .error-list { background: #450a0a; border: 1px solid #7f1d1d; border-radius: 6px;
                padding: 0.75rem 1rem; margin-bottom: 1.5rem; color: #fca5a5; font-size: 0.875rem; }
  .error-list li { margin-left: 1rem; }
  .success { background: #052e16; border: 1px solid #166534; border-radius: 6px;
             padding: 1.5rem; color: #86efac; text-align: center; }
  .success h2 { font-size: 1.1rem; margin-bottom: 0.5rem; }
  .success a { color: #6ee7b7; }
</style>
</head>
<body>
<div class="card">
<?php if ($success): ?>
  <div class="success">
    <h2>Setup complete!</h2>
    <p>config.php written, tables created, and this file has been deleted.</p>
    <p style="margin-top:1rem"><a href="/hub/admin/login.php">Go to admin &rarr;</a></p>
  </div>
<?php else: ?>
  <h1>Hub Setup</h1>
  <p class="sub">Run once — writes config.php, creates database tables, and self-destructs.</p>

  <?php if (!empty($errors)): ?>
    <div class="error-list"><ul><?php foreach ($errors as $e): ?><li><?= htmlspecialchars($e) ?></li><?php endforeach; ?></ul></div>
  <?php endif; ?>

  <form method="POST">
    <p class="section">Database</p>
    <div class="field">
      <label for="db_host">Host</label>
      <input type="text" id="db_host" name="db_host" value="<?= htmlspecialchars($_POST['db_host'] ?? 'localhost') ?>">
    </div>
    <div class="field">
      <label for="db_name">Database Name</label>
      <input type="text" id="db_name" name="db_name" required value="<?= htmlspecialchars($_POST['db_name'] ?? '') ?>">
    </div>
    <div class="field">
      <label for="db_user">Username</label>
      <input type="text" id="db_user" name="db_user" required value="<?= htmlspecialchars($_POST['db_user'] ?? '') ?>">
    </div>
    <div class="field">
      <label for="db_pass">Password</label>
      <input type="password" id="db_pass" name="db_pass" value="<?= htmlspecialchars($_POST['db_pass'] ?? '') ?>">
    </div>

    <hr class="divider">
    <p class="section">Anthropic</p>
    <div class="field">
      <label for="anthropic_api_key">API Key</label>
      <input type="text" id="anthropic_api_key" name="anthropic_api_key" required
             placeholder="sk-ant-..."
             value="<?= htmlspecialchars($_POST['anthropic_api_key'] ?? '') ?>">
    </div>

    <hr class="divider">
    <p class="section">Admin</p>
    <div class="field">
      <label for="hub_url">Hub URL (no trailing slash)</label>
      <input type="text" id="hub_url" name="hub_url" required placeholder="https://onthefritz.us/hub"
             value="<?= htmlspecialchars($_POST['hub_url'] ?? '') ?>">
      <p class="hint">Used by client sites to call the API.</p>
    </div>
    <div class="field">
      <label for="admin_password">Admin Password (min 10 chars)</label>
      <input type="password" id="admin_password" name="admin_password" required minlength="10">
      <p class="hint">This will be bcrypt-hashed and stored in config.php.</p>
    </div>

    <button type="submit">Run Setup</button>
  </form>
<?php endif; ?>
</div>
</body>
</html>
